schema_version: 1

context:
  name: ormar
  version: "0.25.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ormar-${{ version }}.tar.gz
  sha256: cbc7ffe2deda00f1142a2a6db49ffd72fee0ce71bd79250959ae804975420152

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - pydantic >=2.11.9,<3.0.0
    - sqlalchemy >=2.0.40,<3.0.0
    - ormar-utils >=0.1.1
    # from sqlalchemy[ayncio]
    - greenlet >=1

tests:
  - python:
      imports:
        - ormar
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A simple async ORM with fastapi in mind and pydantic validation.
  license: MIT
  license_file: LICENSE.md
  description: |
    The ormar package is an async mini ORM for Python, with support for
    Postgres, MySQL, and SQLite. The main benefit of using ormar includes the
    ability to get an async ORM that can be used with async frameworks
    (fastapi, starlette etc.). Using ormar would simplly workflow with just one
    model to maintain—you don't have to maintain pydantic and other orm model
    (sqlalchemy, peewee, gino etc.)


  homepage: https://github.com/collerek/ormar
  documentation: https://collerek.github.io/ormar/

extra:
  recipe-maintainers:
    - thewchan
